# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f9e3c9d6ab474c05081d87c4338459d3104e9f4b196eeda16b5ea2600a68dccaf1a00ce80bd73e223aad77dd1fc06e90a974073224bf4b1a82f3642ec5715f4

test:
  secret_key_base: e29163b2837e40857ea96450a1c9cfc19eed3eead0434a3cc017fa4b6e17c2d878e4ef4e6c96fe010bbfb6de247bb7b9e5c1992f4f7223d80eca5ab973ace89d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
